### ISSUE TITLE
Permission to use data

### ISSUE THREAD

**Issue by jecece1** [samihanazrul/Supply-Chain-Optimization-with-Machine-Learning#1]
Hi there
I'm Praveen and I'm currently doing a MSc in Business Analytics at the University of Exeter. I'll be starting my dissertation soon and will be working on supply chain and inventory management using analytics. Although I have not yet finalized the data that I'll be using for my project, may I please request you to add a permissive license so that I could use your data if need be? It would be really helpful for my project.

Thanks,
Praveen

**Comment by samihanazrul** [comment]
Hi Praveen,

I have added the MIT License to my repository. You can now use the data for your dissertation. To help showcase the usage of my project, could you please:

1. Star the repository to show your support.
2. Fork the repository to create your own copy, which will be visible on my profile as well.

Thank you, and good luck with your dissertation!

Regards
Samiha

**Comment by jecece1** [comment]
Hi Samiha,
Thank you so much! I'll do as you have mentioned. 

With regards,
Praveen
